sloane: scripts: Update headers_install.sh
 * It fixes:
   * kernel/amazon/sloane/scripts/headers_install.sh: line 40: bionic/libc/kernel/tools/clean_header.py: File or directory does not exist
   * And multiple bionics error like: bionic/libc/include/sys/types.h:39:9: error: unknown type name '__kernel_gid32_t'